//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// xsmnResource.rc에서 사용되고 있습니다.
//
#define HSMN_IDR_ABOUT_BOX								100

#define HSMN_IDR_MAIN_FRAME								128

#define HSMN_IDR_TOOLBAR_FOR_MENU						129

#define HSMN_IDR_PROJECT_TREE_ICON_MODEL				150
#define HSMN_IDR_PROJECT_TREE_ICON_MODULE				151
#define HSMN_IDR_PROJECT_TREE_ICON_BLOCK				152

#define HSMN_IDR_EVENT_LIST_ICON_INFO					153
#define HSMN_IDR_EVENT_LIST_ICON_ERROR					154

#define HSMN_IDR_TOOL_BUTTON_NEW_N						200
#define HSMN_IDR_TOOL_BUTTON_NEW_H						201
#define HSMN_IDR_TOOL_BUTTON_NEW_P						202
#define HSMN_IDR_TOOL_BUTTON_OPEN_N						204
#define HSMN_IDR_TOOL_BUTTON_OPEN_H						205
#define HSMN_IDR_TOOL_BUTTON_OPEN_P						206
#define HSMN_IDR_TOOL_BUTTON_ALIGN_LEFT_N				208
#define HSMN_IDR_TOOL_BUTTON_ALIGN_LEFT_H				209
#define HSMN_IDR_TOOL_BUTTON_ALIGN_LEFT_P				210
#define HSMN_IDR_TOOL_BUTTON_ALIGN_TOP_N				212
#define HSMN_IDR_TOOL_BUTTON_ALIGN_TOP_H				213
#define HSMN_IDR_TOOL_BUTTON_ALIGN_TOP_P				214
#define HSMN_IDR_TOOL_BUTTON_ALIGN_RIGHT_N				216
#define HSMN_IDR_TOOL_BUTTON_ALIGN_RIGHT_H				217
#define HSMN_IDR_TOOL_BUTTON_ALIGN_RIGHT_P				218
#define HSMN_IDR_TOOL_BUTTON_ALIGN_BOTTOM_N				220
#define HSMN_IDR_TOOL_BUTTON_ALIGN_BOTTOM_H				221
#define HSMN_IDR_TOOL_BUTTON_ALIGN_BOTTOM_P				222
#define HSMN_IDR_TOOL_BUTTON_SAVE_N						224
#define HSMN_IDR_TOOL_BUTTON_SAVE_H						225
#define HSMN_IDR_TOOL_BUTTON_SAVE_P						226
#define HSMN_IDR_TOOL_BUTTON_UNDO_N						228
#define HSMN_IDR_TOOL_BUTTON_UNDO_H						229
#define HSMN_IDR_TOOL_BUTTON_UNDO_P						230
#define HSMN_IDR_TOOL_BUTTON_CUT_N						232
#define HSMN_IDR_TOOL_BUTTON_CUT_H						233
#define HSMN_IDR_TOOL_BUTTON_CUT_P						234
#define HSMN_IDR_TOOL_BUTTON_COPY_N						236
#define HSMN_IDR_TOOL_BUTTON_COPY_H						237
#define HSMN_IDR_TOOL_BUTTON_COPY_P						238
#define HSMN_IDR_TOOL_BUTTON_PASTE_N					240
#define HSMN_IDR_TOOL_BUTTON_PASTE_H					241
#define HSMN_IDR_TOOL_BUTTON_PASTE_P					242
#define HSMN_IDR_TOOL_BUTTON_COMPILE_N					244
#define HSMN_IDR_TOOL_BUTTON_COMPILE_H					245
#define HSMN_IDR_TOOL_BUTTON_COMPILE_P					246
#define HSMN_IDR_TOOL_BUTTON_RUN_N						248
#define HSMN_IDR_TOOL_BUTTON_RUN_H						249
#define HSMN_IDR_TOOL_BUTTON_RUN_P						250
#define HSMN_IDR_TOOL_BUTTON_CLOSE_N					252
#define HSMN_IDR_TOOL_BUTTON_CLOSE_H					253
#define HSMN_IDR_TOOL_BUTTON_CLOSE_P					254
#define HSMN_IDR_TOOL_BUTTON_REDO_N						256
#define HSMN_IDR_TOOL_BUTTON_REDO_H						257
#define HSMN_IDR_TOOL_BUTTON_REDO_P						258
#define HSMN_IDR_TOOL_BUTTON_SETTING_N					260
#define HSMN_IDR_TOOL_BUTTON_SETTING_H					261
#define HSMN_IDR_TOOL_BUTTON_SETTING_P					262
#define HSMN_IDR_TOOL_BUTTON_HELP_N						264
#define HSMN_IDR_TOOL_BUTTON_HELP_H						265
#define HSMN_IDR_TOOL_BUTTON_HELP_P						266
#define HSMN_IDR_TOOL_BUTTON_SAME_SIZE_N				268
#define HSMN_IDR_TOOL_BUTTON_SAME_SIZE_H				269
#define HSMN_IDR_TOOL_BUTTON_SAME_SIZE_P				270
#define HSMN_IDR_TOOL_BUTTON_SAME_WIDTH_N				272
#define HSMN_IDR_TOOL_BUTTON_SAME_WIDTH_H				273
#define HSMN_IDR_TOOL_BUTTON_SAME_WIDTH_P				274
#define HSMN_IDR_TOOL_BUTTON_SAME_HEIGHT_N				276
#define HSMN_IDR_TOOL_BUTTON_SAME_HEIGHT_H				277
#define HSMN_IDR_TOOL_BUTTON_SAME_HEIGHT_P				278

#define HSMN_IDR_CAPTION_ICON_ACTIVE					291
#define HSMN_IDR_CAPTION_ICON_INACTIVE					292

#define HSMN_IDR_LOGO_IMAGE								293
#define HSMN_IDR_BACKGROUND								294

#define HSMN_IDR_LIBRARY_GROUP_EXPANED					295
#define HSMN_IDR_LIBRARY_GROUP_COLLAPSED				296
#define HSMN_IDR_LIBRARY_BLOCK_DRAG_IMAGE				297
#define HSMN_IDR_TAG_AUTHOR_ICON						298

#define HSMN_IDR_PROJECT_POPUP							601

#define HSMN_IDR_LEVEL_VIEW_CURSOR						602

#define HSMN_IDC_DUMMY_TOOL_BUTTON						32771
#define HSMN_IDC_VIEW_PROJECT_PANE						32772
#define HSMN_IDC_VIEW_LIBRARY_PANE						32773
#define HSMN_IDC_VIEW_PROPERTY_PANE						32774
#define HSMN_IDC_VIEW_LOG_PANE							32775
#define HSMN_IDC_PROJECT_COMPILE						32776
#define HSMN_IDC_PROJECT_DOWNLOAD						32777
#define HSMN_IDC_TOOL_SETTINGS							32778
#define HSMN_IDC_FORMAT_ALIGN_LEFT						32780
#define HSMN_IDC_FORMAT_ALIGN_RIGHT						32781
#define HSMN_IDC_FORMAT_ALIGN_TOP						32782
#define HSMN_IDC_FORMAT_ALIGN_BOTTOM					32783
#define HSMN_IDC_FORMAT_MAKE_SAME_SIZE					32784
#define HSMN_IDC_FORMAT_MAKE_SAME_WIDTH					32785
#define HSMN_IDC_FORMAT_MAKE_SAME_HEIGHT				32786
#define HSMN_IDC_FORMAT_ROTATE_BLOCK					32787
#define HSMN_IDC_SET_AS_ACTIVE_MODEL					32788
#define HSMN_IDC_CLOSE_MODEL							32789
#define HSMN_IDC_VIEW_MONITORING_PANE					32790
#define HSMN_IDC_TOOL_TAG_AUTOR							32791
#define HSMN_IDC_TOOL_START_MONITORING					32792
#define HSMN_IDC_TOOL_STOP_MONITORING					32793
#define HSMN_IDC_PROJECT_PARAMETERS						32794

#define HSMN_IDC_WINDOWS_CLOSE_ALL						32799
#define HSMN_IDC_WINDOWS_MANAGER						32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        603
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
